Workflow test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,28 +30,98 @@ env:
   # BUILD_PATH: subfolder
 
 jobs:
-  lint:
+  check:
+    name: astro check
     runs-on: ubuntu-latest
-    environment: deploy
+    timeout-minutes: 5
     steps:
-      - name: Checkout Commit
+      - name: Check out repository
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            echo "lockfile=yarn.lock" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            echo "lockfile=package-lock.json" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
           node-version: "20"
           cache: ${{ steps.detect-package-manager.outputs.manager }}
           cache-dependency-path: ${{ env.BUILD_PATH }}/${{ steps.detect-package-manager.outputs.lockfile }}
-      - name: Install pnpm
-        run: npm i --location=global pnpm
       - name: Install dependencies
-        run: pnpm install
-      - name: Check
-        run: pnpm astro check
-        env:
-          LOCALE_CI: en
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+        working-directory: ${{ env.BUILD_PATH }}
+      - name: Status
+        run: git status
+      - name: Astro Check
+        run: |
+          ${{ steps.detect-package-manager.outputs.runner }} astro check \
+            --minimumFailingSeverity hint \
+            --minimumSeverity hint
+
+#
+#
+#
+#      - name: Setup PNPM
+#        uses: pnpm/action-setup@v3
+#
+#      - name: Setup Node
+#        uses: actions/setup-node@v4
+#        with:
+#          node-version: 18
+#          cache: "pnpm"
+#
+#      - name: Install dependencies
+#        run: pnpm install
+#
+#      - name: Build
+#        run: pnpm run build
+#
+#      - name: Status
+#        run: git status
+#
+#      - name: astro check
+#        run: pnpm run test:check-examples
+#
+#
+#  lint:
+#    runs-on: ubuntu-latest
+#    environment: deploy
+#    steps:
+#      - name: Checkout Commit
+#        uses: actions/checkout@v4
+#        with:
+#          fetch-depth: 0
+#      - name: Setup Node
+#        uses: actions/setup-node@v4
+#        with:
+#          node-version: "20"
+#          cache: ${{ steps.detect-package-manager.outputs.manager }}
+#          cache-dependency-path: ${{ env.BUILD_PATH }}/${{ steps.detect-package-manager.outputs.lockfile }}
+#      - name: Install pnpm
+#        run: npm i --location=global pnpm
+#      - name: Install dependencies
+#        run: pnpm install
+#      - name: Check
+#        run: pnpm astro check
+#        env:
+#          LOCALE_CI: en
 
 #  build:
 #    name: Build
